//
//  Currencies.swift
//  R3PIBasket
//
//  Created by Stephan Korner on 29.06.18.
//  Copyright © 2018 Ideen Kaffee Korner. All rights reserved.
//

import Foundation

enum Currency: String, EnumCollection {
    
    case AED = "AED" // United Arab Emirates Dirham
    case AFN = "AFN" // Afghan Afghani
    case ALL = "ALL" // Albanian Lek
    case AMD = "AMD" // Armenian Dram
    case ANG = "ANG" // Netherlands Antillean Guilder
    case AOA = "AOA" // Angolan Kwanza
    case ARS = "ARS" // Argentine Peso
    case AUD = "AUD" // Australian Dollar
    case AWG = "AWG" // Aruban Florin
    case AZN = "AZN" // Azerbaijani Manat
    case BAM = "BAM" // Bosnia-Herzegovina Convertible Mark
    case BBD = "BBD" // Barbadian Dolla>
    case BDT = "BDT" // Bangladeshi Tak>
    case BGN = "BGN" // Bulgarian Lev
    case BHD = "BHD" // Bahraini Dinar
    case BIF = "BIF" // Burundian Franc
    case BMD = "BMD" // Bermudan Dollar
    case BND = "BND" // Brunei Dollar
    case BOB = "BOB" // Bolivian Bolivion
    case BRL = "BRL" // Brazilian Real
    case BSD = "BSD" // Bahamian Dollar
    case BTN = "BTN" // Bhutanese Ngulton
    case BWP = "BWP" // Botswanan Pula
    case BYR = "BYR" // Belarusian Rubl
    case BZD = "BZD" // Belize Dollar
    case CAD = "CAD" // Canadian Dollar
    case CDF = "CDF" // Congolese Franc
    case CHF = "CHF" // Swiss Franc
    case CLF = "CLF" // Chilean Unit of Account
    case CLP = "CLP" // Chilean Peso
    case CNY = "CNY" // Chinese Yuan
    case COP = "COP" // Colombian Peso
    case CRC = "CRC" // Costa Rican ColÃ³n
    case CUP = "CUP" // Cuban Peso
    case CVE = "CVE" // Cape Verdean Escudo
    case CZK = "CZK" // Czech Republic Koruna
    case DJF = "DJF" // Djiboutian Franc
    case DKK = "DKK" // Danish Krone
    case DOP = "DOP" // Dominican Peso
    case DZD = "DZD" // Algerian Dinar
    case EGP = "EGP" // Egyptian Pound
    case ETB = "ETB" // Ethiopian Birr
    case EUR = "EUR" // Euro
    case FJD = "FJD" // Fijian Dollar
    case FKP = "FKP" // Falkland Islands Pound
    case GBP = "GBP" // British Pound Sterling
    case GEL = "GEL" // Georgian Lari
    case GHS = "GHS" // Ghanaian Cedi
    case GIP = "GIP" // Gibraltar Pound
    case GMD = "GMD" // Gambian Dalasi
    case GNF = "GNF" // Guinean Franc
    case GTQ = "GTQ" // Guatemalan Quetza
    case GYD = "GYD" // Guyanaese Dollar
    case HKD = "HKD" // Hong Kong Dollar
    case HNL = "HNL" // Honduran Lempira
    case HRK = "HRK" // Croatian Kuna
    case HTG = "HTG" // Haitian Gourde
    case HUF = "HUF" // Hungarian Forint
    case IDR = "IDR" // Indonesian Rupiah
    case ILS = "ILS" // Israeli New Sheq
    case INR = "INR" // Indian Rupee
    case IQD = "IQD" // Iraqi Dinar
    case IRR = "IRR" // Iranian Rial
    case ISK = "ISK" // Icelandic KrÃ³na
    case JEP = "JEP" // Jersey Pound
    case JMD = "JMD" // Jamaican Dollar
    case JOD = "JOD" // Jordanian Dinar
    case JPY = "JPY" // Japanese Yen
    case KES = "KES" // Kenyan Shilling
    case KGS = "KGS" // Kyrgystani Som
    case KHR = "KHR" // Cambodian Riel
    case KMF = "KMF" // Comorian Franc
    case KPW = "KPW" // North Korean Won
    case KRW = "KRW" // South Korean Won
    case KWD = "KWD" // Kuwaiti Dinar
    case KYD = "KYD" // Cayman Islands Doion
    case KZT = "KZT" // Kazakhstani Tenge
    case LAK = "LAK" // Laotian Kip
    case LBP = "LBP" // Lebanese Pound
    case LKR = "LKR" // Sri Lankan Rupee
    case LRD = "LRD" // Liberian Dollar
    case LSL = "LSL" // Lesotho Loti
    case LTL = "LTL" // Lithuanian Litas
    case LVL = "LVL" // Latvian Lats
    case LYD = "LYD" // Libyan Dinar
    case MAD = "MAD" // Moroccan Dirham
    case MDL = "MDL" // Moldovan Leu
    case MGA = "MGA" // Malagasy Ariary
    case MKD = "MKD" // Macedonian Denar
    case MMK = "MMK" // Myanma Kyat
    case MNT = "MNT" // Mongolian Tugrik
    case MOP = "MOP" // Macanese Pataca
    case MRO = "MRO" // Mauritanian Ouguin>
    case MUR = "MUR" // Mauritian Rupee
    case MVR = "MVR" // Maldivian Rufiyaa
    case MWK = "MWK" // Malawian Kwacha
    case MXN = "MXN" // Mexican Peso
    case MYR = "MYR" // Malaysian Ringgit
    case MZN = "MZN" // Mozambican Metical
    case NAD = "NAD" // Namibian Dollar
    case NGN = "NGN" // Nigerian Naira
    case NIO = "NIO" // Nicaraguan CÃ³rdoba
    case NOK = "NOK" // Norwegian Krone
    case NPR = "NPR" // Nepalese Rupee
    case NZD = "NZD" // New Zealand Dollar
    case OMR = "OMR" // Omani Rial
    case PAB = "PAB" // Panamanian Balboa
    case PEN = "PEN" // Peruvian Nuevo Sol
    case PGK = "PGK" // Papua New Guinean Kina
    case PHP = "PHP" // Philippine Peso
    case PKR = "PKR" // Pakistani Rupee
    case PLN = "PLN" // Polish Zloty
    case PYG = "PYG" // Paraguayan Guarani
    case QAR = "QAR" // Qatari Rial
    case RON = "RON" // Romanian Leu
    case RSD = "RSD" // Serbian Dinar
    case RUB = "RUB" // Russian Ruble
    case RWF = "RWF" // Rwandan Franc
    case SAR = "SAR" // Saudi Riyal
    case SBD = "SBD" // Solomon Islands Dollar
    case SCR = "SCR" // Seychellois Rupee
    case SDG = "SDG" // Sudanese Pound
    case SEK = "SEK" // Swedish Krona
    case SGD = "SGD" // Singapore Dollar
    case SHP = "SHP" // Saint Helena Pound
    case SLL = "SLL" // Sierra Leonean Leone
    case SOS = "SOS" // Somali Shilling
    case SRD = "SRD" // Surinamese Dollar
    case STD = "STD" // SÃ£o TomÃ© and PrÃ­ncipe Dobra
    case SVC = "SVC" // Salvadoran ColÃ³n
    case SYP = "SYP" // Syrian Pound
    case SZL = "SZL" // Swazi Lilangeni
    case THB = "THB" // Thai Baht
    case TJS = "TJS" // Tajikistani Somoni
    case TMT = "TMT" // Turkmenistani Manat
    case TND = "TND" // Tunisian Dinar
    case TOP = "TOP" // Tongan Pa?anga
    case TRY = "TRY" // Turkish Lira
    case TTD = "TTD" // Trinidad and Tobago Dollar
    case TWD = "TWD" // New Taiwan Dollar
    case TZS = "TZS" // Tanzanian Shilling
    case UAH = "UAH" // Ukrainian Hryvnia
    case UGX = "UGX" // Ugandan Shilling
    case USD = "USD" // United States Dollar
    case UYU = "UYU" // Uruguayan Peso
    case UZS = "UZS" // Uzbekistan Som
    case VEF = "VEF" // Venezuelan BolÃ­var
    case VND = "VND" // Vietnamese Dong
    case VUV = "VUV" // Vanuatu Vatu
    case WST = "WST" // Samoan Tala
    case XAF = "XAF" // CFA Franc BEAC
    case XCD = "XCD" // East Caribbean Dollar
    case XDR = "XDR" // Special Drawing Rights
    case XOF = "XOF" // CFA Franc BCEAO
    case XPF = "XPF" // CFP Franc
    case YER = "YER" // Yemeni Rial
    case ZAR = "ZAR" // South African Rand
    case ZMK = "ZMK" // Zambian Kwacha
    case ZWL = "ZWL" // Zimbabwean Dollar
}
